language: node_js
node_js:
  - "10"

addons:
  chrome: stable

install:
  - npm install

script:
  - npm build


after_success:
  - npm install -g firebase-tools
  - firebase deploy --token "$FIREBASE_TOKEN"
